[package]
name = "crt-core"
version = "0.1.0"
edition = "2024"

[dependencies]
log.workspace = true
vte.workspace = true
alacritty_terminal.workspace = true
portable-pty.workspace = true
anyhow.workspace = true
