[package]
name = "crt-renderer"
version = "0.1.0"
edition = "2024"

[dependencies]
crt-theme = { path = "../crt-theme" }

wgpu.workspace = true
vello.workspace = true
swash.workspace = true
bytemuck.workspace = true
log.workspace = true
