[package]
name = "crt-config"
version = "0.1.0"
edition = "2024"

[dependencies]
toml = { workspace = true }
serde = { workspace = true }
dirs = { workspace = true }
log = { workspace = true }
notify = { workspace = true }
